### ISSUE TITLE
Unable to Install through App Store

### ISSUE THREAD

**Issue by AjayShanker-geek** [apparition47/MailTrackerBlockerApp#4]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. e.g. I'm always frustrated when [...]

Unable to install through the app store. Apple account in USA & Singapore Region.

```
This app is currently not available in your country or region.
```

**Comment by averkiev** [comment]
Looks like the app was removed from the App Store. If that's the case, I wonder why. I paid for the product and it now I cannot re-install it.

**Comment by apparition47** [comment]
@averkiev I apologize for this; I pulled the app because of complaints of Mail crashes. I cannot fix this myself so Apple's intervention is needed in order to fix Mail/MailKit. Apple did mention they have a fix but haven't provided a timeline unfortunately. If you email me (see profile @apparition47), I can provide you access to the app keeping in mind this bug. Alternatively, you should be able to request a refund from the App Store. In either case, I'm expecting to return the app to the App Store once Mail is fixed. You'll need a future version of macOS to use it though (14.4? 15.0? I don't know yet).

**Comment by AjayShanker-geek** [comment]
Do you need testflight testers? I would like to help! Email: ajay_shanker@icloud.com

**Comment by apparition47** [comment]
Apple has fixed a critical bug so I think it's safe to put the app back in the App Store. You'll need the latest Sonoma 14.3 however.
